# BLAS ASSIGNMENT

Use the cell below for all your imports.

In [2]:
import numpy as np
from scipy.linalg.blas import dgemv, ddot, dnrm2

Create a matrix and a vector using NumPy.Their dtype should be double.

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
x = np.array([1, 2, 3], dtype=np.double)

Use BLAS functions to perform matrix-vector multiplication

In [14]:
from scipy.linalg import blas
from scipy.linalg import lapack

z = blas.dgemv(alpha =1.0, a = A, x = x)
z

array([14., 25., 31.])

In [4]:
y = np.zeros_like(x)
alpha = 1.0
beta = 0.0
dgemv(alpha, A, x, beta, y)
print(y)

[0. 0. 0.]


Create two new vectors and calculate their dot product using BLAS functions.

In [10]:
a = np.array([1, 2, 3], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)
result = ddot(a, b)
print(result)

32.0


Compute the L2 norm (Euclidean distance) of a vector using BLAS functions

In [11]:
a = np.array([1, 2, 3], dtype=np.double)
norm = dnrm2(a)
print(norm)

3.7416573867739413


Create a 5x5 symmetric matrix and calculate its eigenvalues and eigenvectors using BLAS functions

In [19]:
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.double)
w = lapack.dsyev(A)
print("Eigenvalues:", w[0])
print("Eigenvectors:", w[1])

Eigenvalues: [-0.51572947  0.17091519 11.34481428]
Eigenvectors: [[ 0.73697623  0.59100905  0.32798528]
 [ 0.32798528 -0.73697623  0.59100905]
 [-0.59100905  0.32798528  0.73697623]]


Given the following matrix `A` and vector `v`: 

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

Solve the system `Ax = b` using the LU decomposition method and BLAS functions

In [28]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)
#lu, piv = lapack.dgetrf(A)
lu = lapack.dgetrf(A)
#x = lapack.dgetri(lu, b)
print(lu)

(array([[ 7.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [ 1.42857143e-01,  8.57142857e-01,  1.71428571e+00],
       [ 5.71428571e-01,  5.00000000e-01, -1.58603289e-16]]), array([2, 2, 2], dtype=int32), 0)


# Merge Sort

In [61]:
import numpy as np
A = np.array([2,5,8,17,19])
B = np.array([1,4,5,7,11,14])

def merge_sort(A,B):
  
            
    return c

In [50]:
n = len(A) + len(B)
c = np.array((1,n))
c

array([ 1, 11])

In [62]:
merge_sort(A,B)

2
1


ValueError: setting an array element with a sequence.

In [122]:
A = [2,5,8,17,19]
B = [1,4,5,7,11]

# le tableau A est le tableau avec la petit dimnesion
def merge_sort(A,B):
    
    c = []
    for i in A: 
        for j in B:
            if i<j:
                c.append(i)
                break;
            else:
                if j in c :
                    pass;
                else:
                    c.append(j)
                

        if i in c:
            pass;
        else:
            c.append(i)



    return c

In [117]:
def merge_sorted_arrays(arr1, arr2):
    """
    Merge two sorted arrays into a single sorted array
    """
    merged_arr = []
    i = j = 0

    # Merge the two arrays by comparing elements
    while i < len(arr1) and j < len(arr2):
        if arr1[i] < arr2[j]:
            merged_arr.append(arr1[i])
            i += 1
        else:
            merged_arr.append(arr2[j])
            j += 1

    # Append remaining elements, if any
    #merged_arr += arr1[i:]
    #merged_arr += arr2[j:]

    return merged_arr


# Example usage
arr1 = [1, 3, 5, 7]
arr2 = [2, 4, 6, 8]
merged_arr = merge_sorted_arrays(arr1, arr2)
print(merged_arr)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]






[1, 2, 3, 4, 5, 6, 7]


In [123]:
merge_sort(A,B)

[1, 2, 4, 5, 5, 7, 8, 11, 17, 19]

In [121]:
merge_sort(B,A)

[1, 2, 4, 5, 5, 7, 8, 11, 14]

In [142]:
def merge_two_sorted_arrays(nums1, nums2):
    m = len(nums1)
    n = len(nums2)
    nums = np.array(n+m)
    while m > 0 and n > 0 : 
        if nums1[m-1] >= nums2[n-1]:
            nums[n+m-1] = nums1[m-1]
            
        else:
            nums[n+m-1] = nums2[n-1]
            n = n - 1 
            if n > 0 :
                nums[0:n] = nums2[:n]
            m = m - 1 

    return nums1

In [143]:
merge_two_sorted_arrays(A,B)

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [146]:
A = [2,5,8,17,19]
B = [1,4,5,7,11]

# le tableau A est le tableau avec la petit dimnesion
def merge_sort(A,B):
    
    
    m = len(A)
    l = len(B)
    n = len(A) + len(B)
    c = np.zeros(n)
    while(l>0):
        if A[l-1]<B[l-1]:
            c[l-1] = B[l-1]
        else:
            c[l-1] = A[l-1]
        l = l-1
    
    for i in range(l,m):
        c[i-1] = A[i-1]
    return c


In [147]:
merge_sort(A,B)

array([ 2.,  5.,  8., 17., 19.,  0.,  0.,  0.,  0., 19.])

In [148]:
def merge(A, B):
    c = np.empty(len(A) + len(B), dtype=A.dtype)
    i = j = k = 0
    while i < len(A) and j < len(B):
        if A[i] <= B[j]:
            c[k] = A[i]
            i += 1
        else:
            c[k] = B[j]
            j += 1
        k += 1
    while i < len(A):
        c[k] = A[i]
        i += 1
        k += 1
    while j < len(B):
        c[k] = B[j]
        j += 1
        k += 1
    return c



        

The Master theorem is used to analyze the time complexity of recursive functions. In the case of the merge() function, which merges two sorted arrays into a single sorted array, the input size is n and the function calls two sub-problems of size n/2. Using the Master theorem, we can express the complexity of merge() as T(n) = 2T(n/2) + O(n). If we can show that the non-recursive part of the function has a complexity of O(n^c) for some constant c > 1, we can conclude that the complexity of merge() is O(n^c). The creation of the resulting array has a complexity of O(n), which is O(n^1), so we can choose c = 1.1, for example. For this value of c, we have c > log_b(a) (where a = 2 and b = 2), so the complexity of merge() is O(n^1.1). This is slightly higher than O(n) but lower than O(n log n).

# Binary search

In [150]:
def binarySearch(array, target): #returns the index or the target 
    low = array[0]
    high = array[len(array)-1]
    if array[0] == target:
            return 0
    elif array[len(array)-1] == target:
        return len(array)-1
    else:
        while(low <= high):
            mid = int((low+high)/2)
            if array[mid]==target:
                return mid
            elif array[mid] > target:
                high = mid -1
            elif array[mid] < target:
                low = mid +1
        return -1  #returns -1 if the target does not exist

The while loop repeats until either the target is found or the size of the remaining subarray becomes 0. Since the size of the remaining subarray is halved at each iteration of the loop, the maximum number of iterations is log2(n). Each iteration takes constant time, so the total time complexity of the loop is O(log n)